from routes.index_dashkit import index_dashkit
from routes.data_preview_dashkit import data_preview_dashkit
from routes.process_data_dashkit import process_data_dashkit, download_pca_dashkit
from routes.select_model_dashkit import select_model_dashkit
from routes.bcvi_dashkit import bcvi_dashkit, download_bcvi_dashkit